unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

## Color Setting
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

# 윈도우 위치 바뀔 때 번호 재부여, 번호는 1 부터 
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

## window 사이즈 조정
# window 의 사이즈를 가장 작은 session 크기에 맞게 조정
set -w -g aggressive-resize
# 새 window의 history limit 설정
set -g history-limit 50000

## Mouse event 처리
# tmux 에서 mouse event를 처리 (키 바인딩과 연결)
set -g mouse on

## Copy to system clipboard 
set -s set-clipboard on 
# set -s set-clipboard external 
# set -g allow-passthrough on 


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -ogq @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# status left style
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_mantle},bold]  #S },#{#[bg=#{@thm_mantle},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# status right style
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# window style
# set -wg automatic-rename on
# set -g automatic-rename-format ''
set -g window-status-separator '|'
set -g status-justify 'absolute-centre'
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_number ""
set -g @catppuccin_window_text "#[fg=#{@thm_rosewater},bg=#{@thm_mantle}] #I#{?#{!=:#{window_name},},: #W,}"
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bg=#{@thm_peach}] #I#{?#{!=:#{window_name},},: #W,}"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
